services:
  db:
    image: postgres:17-alpine
    container_name: chapa_db
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - chapaData:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - chapa_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:latest
    container_name: chapa_redis
    ports:
      - "6379:6379"
    networks:
      - chapa_net

networks:
  chapa_net:
volumes:
  chapaData:
